# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-jjXTt7MMKN-d4Ny44TZyiXq2Lu8b6N2
"""







!pip install sentencepiece

!pip install sacremoses

from transformers import MarianMTModel, MarianTokenizer

model_name = 'Helsinki-NLP/opus-mt-en-de'

tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

text = "Good Morning Mam."

inputs = tokenizer(text, return_tensors="pt", padding=True)

translated = model.generate(**inputs)

output = tokenizer.decode(translated[0], skip_special_tokens=True)

print("Translated (English to Hindi ):", output)

from transformers import MarianMTModel, MarianTokenizer

# Load the English-to-French model
model_name = 'Helsinki-NLP/opus-mt-en-fr'
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

# Input text
text = "Good Morning Mam."

# Tokenize and generate translation
inputs = tokenizer(text, return_tensors="pt", padding=True)
translated = model.generate(**inputs)
output = tokenizer.decode(translated[0], skip_special_tokens=True)

# Print the result
print("Translated (English to Hindi):", output)



"""**  ENGLISH TO HINDI TRANSLATION"""

from transformers import MarianMTModel, MarianTokenizer

model_name = 'Helsinki-NLP/opus-mt-en-hi'  # Hindi translation model
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

text = "Good Morning Mam."
inputs = tokenizer(text, return_tensors="pt", padding=True)

translated = model.generate(**inputs)
output = tokenizer.decode(translated[0], skip_special_tokens=True)

print("Translated (English to Hindi):", output)

